version: '3.8'

services:
  postgres:
    container_name: rprodg_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rprodgdb
